-- SQL Schema for IT Service Web App on Hostinger (MySQL)
-- Version 3: Fixed COMMENT syntax error.
-- Generated by Gemini

SET FOREIGN_KEY_CHECKS=0;

-- Drop old and new tables if they exist
DROP TABLE IF EXISTS `posts`;
DROP TABLE IF EXISTS `post_categories`;
DROP TABLE IF EXISTS `pc_builds`;
DROP TABLE IF EXISTS `quotation_requests`;
DROP TABLE IF EXISTS `projects`;
DROP TABLE IF EXISTS `services`;
DROP TABLE IF EXISTS `order_items`;
DROP TABLE IF EXISTS `orders`;
DROP TABLE IF EXISTS `articles`;
DROP TABLE IF EXISTS `article_categories`;
DROP TABLE IF EXISTS `products`;
DROP TABLE IF EXISTS `product_categories`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `homepage_settings`;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE `users` (
  `uid` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `displayName` VARCHAR(255) NULL,
  `role` VARCHAR(50) NOT NULL DEFAULT 'customer' COMMENT 'Can be ''admin'' or ''customer''',
  `photoURL` TEXT NULL,
  `phoneNumber` VARCHAR(25) NULL,
  `address` JSON NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `product_categories`
-- -----------------------------------------------------
CREATE TABLE `product_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL UNIQUE,
  `description` TEXT NULL,
  `parentCategoryId` INT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`parentCategoryId`) REFERENCES `product_categories`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `products`
-- -----------------------------------------------------
CREATE TABLE `products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `price` DECIMAL(12, 2) NOT NULL,
  `stock` INT NOT NULL DEFAULT 0,
  `images` JSON NULL COMMENT 'Array of image URLs',
  `categoryId` INT NULL,
  `brand` VARCHAR(100) NULL,
  `specs` JSON NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`categoryId`) REFERENCES `product_categories`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `article_categories`
-- -----------------------------------------------------
CREATE TABLE `article_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `articles`
-- -----------------------------------------------------
CREATE TABLE `articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL UNIQUE,
  `content` LONGTEXT NULL,
  `summary` TEXT NULL,
  `imageUrl` TEXT NULL,
  `authorId` VARCHAR(255) NULL,
  `categoryId` INT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'draft' COMMENT 'e.g., draft, published, archived',
  `publishedAt` DATETIME NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`authorId`) REFERENCES `users`(`uid`) ON DELETE SET NULL,
  FOREIGN KEY (`categoryId`) REFERENCES `article_categories`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
CREATE TABLE `orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(255) NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'pending' COMMENT 'Can be ''pending'', ''processing'', ''shipped'', ''delivered'', ''cancelled''',
  `totalAmount` DECIMAL(12, 2) NOT NULL,
  `customerInfo` JSON NOT NULL,
  `shippingAddress` JSON NOT NULL,
  `paymentDetails` JSON NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`userId`) REFERENCES `users`(`uid`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `order_items`
-- -----------------------------------------------------
CREATE TABLE `order_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orderId` INT NOT NULL,
  `productId` INT NOT NULL,
  `quantity` INT NOT NULL,
  `priceAtPurchase` DECIMAL(12, 2) NOT NULL,
  `productName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`orderId`) REFERENCES `orders`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`productId`) REFERENCES `products`(`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `services`
-- -----------------------------------------------------
CREATE TABLE `services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `pricing` JSON NULL,
  `imageUrl` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `projects`
-- -----------------------------------------------------
CREATE TABLE `projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `images` JSON NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `clientName` VARCHAR(255) NULL,
  `serviceIds` JSON NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `quotation_requests`
-- -----------------------------------------------------
CREATE TABLE `quotation_requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(25) NULL,
  `message` TEXT NOT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'new' COMMENT 'Can be ''new'', ''contacted'', or ''closed''',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `pc_builds`
-- -----------------------------------------------------
CREATE TABLE `pc_builds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(255) NULL,
  `buildName` VARCHAR(255) NULL,
  `components` JSON NULL,
  `totalPrice` DECIMAL(12, 2) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`userId`) REFERENCES `users`(`uid`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `homepage_settings`
-- -----------------------------------------------------
CREATE TABLE `homepage_settings` (
  `setting_key` VARCHAR(100) NOT NULL,
  `setting_value` JSON NULL,
  PRIMARY KEY (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --- Insert default homepage settings ---
INSERT INTO `homepage_settings` (`setting_key`, `setting_value`) VALUES
('heroBanner', JSON_OBJECT('title', 'Your Title', 'subtitle', 'Your Subtitle', 'imageUrl', '/path/to/image.jpg', 'cta', JSON_OBJECT('text', 'Shop Now', 'link', '/shop'))),
('featuredProjects', JSON_ARRAY()),
('testimonials', JSON_ARRAY()),
('whyChooseUs', JSON_OBJECT('title', 'Why Choose Us', 'reasons', JSON_ARRAY())),
('featuredServices', JSON_ARRAY());

SET FOREIGN_KEY_CHECKS=1;
